DROP TABLE IF EXISTS `car` CASCADE;

CREATE TABLE `car` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`make`  VARCHAR(255) NOT NULL,
	`num_Doors` INTEGER NOT NULL, 
 	`colour` VARCHAR(255),
 	`miles` BIGINT NOT NULL
 );